### ISSUE TITLE
bug in DObj.data (v 0.1.19) 

### ISSUE THREAD

**Issue by PhysicsBeyond** [ICOS-Carbon-Portal/pylib#158] opened 2023-10-20 10:29 UTC
Hello!

I have encountered a bug in a code today that has been running yesterday without problems. The problem is caused by DObj.data in an internal call that tries to access `self.meta['specification']['format']['uri'].split('/')[-1]`. Apparently, the `uri` key does not exist.

Here is a minimal code example causing the error (username and password need to be replaced with own access data)

```
from icoscp.cpauth.authentication import Authentication
from icoscp.cpb.dobj import Dobj as dobj

# Authentication 
Authentication(username='user', password='*****')

#Test access
do = dobj('https://meta.icos-cp.eu/objects/j7-Lxlln8_ysi4DEV8qine_v')

# Fetch the specified data.
obtained_data = do.data
```

and here is the traceback:
![image](https://github.com/ICOS-Carbon-Portal/pylib/assets/104894069/8bd63567-7e65-4c43-ae40-938c371378ff)

Many thanks for your help!

**Comment by claudiodonofrio** [comment] 2023-10-20 10:36
Many thanks for reporting this, we will take this up as soon as possible.

**Comment by mirzov** [comment] 2023-10-20 14:21
This was a regression due to a backwards-incompatible metadata change. The affected metadata use case unfortunately "flew under the radar" when checking for implications of the change. Has been fixed by https://github.com/ICOS-Carbon-Portal/meta/commit/c95d7512c95fc0227b7e236448dddeefa853b28d

**Closed by mirzov** 2023-10-20 14:21 UTC
